# Fixing Links Notebook

Before running this notebook, make sure to run the following command in the terminal to install the required packages:

```bash
bundle install
make all
ruby parse_htmlproofer_log.rb 
```

Each command should be run separately and the final two commands create files for all the htmlproofer errors and warnings. This notebook loads the final csv file to help you see what links exists. You will also need to install the `pandas` library if you haven't already. You can do this by running:

```bash
pip install pandas
```

## Load Libraries and Data

In [46]:
import pandas as pd

In [59]:
df = pd.read_csv("htmlproofer-report.csv")
# Lower case the column names
df.columns = df.columns.str.lower()
print(f"Number of errors: {len(df)}")

Number of errors: 212

In [60]:
message_counts = df.message.value_counts().reset_index()
print(f"Number of unique error messages: {len(message_counts)}")
message_counts[(message_counts['count']>1)]

Number of unique error messages: 150

                                              message  count
0         http://www.python.org/ is not an HTTPS link      6
1   http://niche-canada.org/2018/03/23/a-decade-of...      4
2   http://clionauta.hypotheses.org/16979 is not a...      4
3   External link https://github.com/orgs/programm...      4
4   External link https://central.github.com/mac/l...      4
5   internally linking to nocoes-basicas-paginas-w...      4
6   image /images/website/index/woman-using-tabula...      3
7   http://www.loc.gov/maps/collections is not an ...      3
8   http://programminghistorian.org/ is not an HTT...      3
9   http://www.crummy.com/software/BeautifulSoup/ ...      3
10  External link https://internetarchive.readthed...      3
11  internally linking to /en/lessons/building-sta...      3
12  internally linking to /en/lessons/creating-net...      3
13  image /images/website/individual/red-bird-on-b...      2
14  image /images/website/ipp/bird-with-eggs-nest....      2
15  http://dx.doi.org/10.1145/2682571.2797068 is n...      2
16  http://www.gazetteer.org.uk/index.php is not a...      2
17  http://support.apple.com/kb/ht1427 is not an H...      2
18  http://www.gov.pe.ca/gis/download.php3?name=fo...      2
19  http://en.wikipedia.org/wiki/UTF-8 is not an H...      2
20              http://tropy.org is not an HTTPS link      2
21  External link https://internetarchive.readthed...      2
22  External link https://textcreationpartnership....      2
23  External link https://www.hastac.org/blogs/har...      2
24  internally linking to /fr/consignes-auteurs#ét...      2
25  internally linking to /pt/directrizes-autor#et...      2
26  internally linking to /es/guia-para-autores#pa...      2
27    internally linking to ipp, which does not exist      2
28  internally linking to /en/lessons/clustering-w...      2
29  internally linking to /en/lessons/text-mining-...      2
30  internally linking to /en/lessons/jupyter-note...      2
31  internally linking to /en/lessons/intro-to-pow...      2
32  internally linking to /en/lessons/extracting-i...      2
33  internally linking to #google-vision-2; the fi...      2
34  internally linking to /en/lessons/intro-to-bea...      2
35  internally linking to /en/lessons/intro-to-bas...      2
36  internally linking to #Final-code; the file ex...      2
37  internally linking to support-us#institutional...      2
38  internally linking to #paso-3-selecion-sistema...      2
39  internally linking to introduccion-a-bash, whi...      2
40  internally linking to #Apêndice:AMatemáticapor...      2

In [61]:
file_counts = df.file.value_counts().reset_index()
print(f"Number of unique files with errors: {len(file_counts)}")
file_counts[file_counts['count']>1]

Number of unique files with errors: 123

                                                 file  count
0   _site/pt/licoes/introducao-instalacao-python/i...      6
1   _site/en/lessons/collaborative-blog-with-jekyl...      5
2   _site/en/lessons/retired/intro-to-augmented-re...      4
3                      _site/en/contribute/index.html      4
4   _site/en/lessons/interactive-data-visualizatio...      4
5   _site/en/lessons/retired/graph-databases-and-S...      4
6                                 _site/pt/index.html      3
7   _site/en/lessons/applied-archival-downloading-...      3
8   _site/en/lessons/detecting-text-reuse-with-pas...      3
9   _site/en/lessons/exploring-and-analyzing-netwo...      3
10  _site/en/lessons/preserving-your-research-data...      3
11             _site/pt/directrizes-editor/index.html      3
12  _site/en/lessons/retired/getting-started-with-...      3
13  _site/es/lecciones/mineria-de-datos-en-interne...      3
14  _site/es/lecciones/retirada/introduccion-contr...      3
15              _site/en/author-guidelines/index.html      3
16       _site/en/lesson-retirement-policy/index.html      3
17  _site/en/lessons/clustering-visualizing-word-e...      3
18            _site/en/lessons/json-and-jq/index.html      3
19  _site/en/lessons/ocr-with-google-vision-and-te...      3
20                     _site/en/supporters/index.html      3
21          _site/en/translator-guidelines/index.html      3
22  _site/es/lecciones/construir-repositorio-de-fu...      3
23  _site/es/lecciones/retirada/sparql-datos-abier...      3
24    _site/es/politica-retirada-lecciones/index.html      3
25        _site/pt/licoes-politica-remocao/index.html      3
26                             _site/fr/pi/index.html      2
27              _site/en/editor-guidelines/index.html      2
28  _site/en/lessons/introduction-and-installation...      2
29       _site/en/lessons/mac-installation/index.html      2
30   _site/en/lessons/windows-installation/index.html      2
31                       _site/en/research/index.html      2
32                    _site/es/guia-editor/index.html      2
33                  _site/es/investigacion/index.html      2
34  _site/es/lecciones/gestionar-fuentes-primarias...      2
35  _site/fr/lecons/detecter-la-reutilisation-de-t...      2
36  _site/fr/lecons/installation-windows-py/index....      2
37  _site/fr/lecons/introduction-et-installation/i...      2
38                      _site/fr/recherche/index.html      2
39          _site/pt/licoes/instalacao-mac/index.html      2
40                       _site/pt/pesquisa/index.html      2
41  _site/en/lessons/crowdsourced-data-normalizati...      2
42  _site/en/lessons/data-mining-the-internet-arch...      2
43  _site/en/lessons/beginners-guide-to-twitter-da...      2
44  _site/en/lessons/corpus-analysis-with-spacy/in...      2
45  _site/en/lessons/shiny-leaflet-newspaper-map-t...      2
46  _site/es/lecciones/introduccion-a-powershell/i...      2
47  _site/es/lecciones/lectura-escalable-de-datos-...      2
48  _site/es/lecciones/topic-modeling-y-mallet/ind...      2
49  _site/fr/lecons/concevoir-base-donnees-nodegoa...      2
50  _site/fr/lecons/enrichir-donnees-reconciliatio...      2
51  _site/fr/lecons/generer-jeu-donnees-texte-ocr/...      2
52  _site/pt/licoes/analise-correspondencia-pesqui...      2
53  _site/pt/licoes/introducao-jupyter-notebooks/i...      2

In [62]:
file_counts_df = df.file.value_counts().reset_index()
file_counts_df['count_index'] = file_counts_df.index

file_counts_df

                                                  file  count  count_index
0    _site/pt/licoes/introducao-instalacao-python/i...      6            0
1    _site/en/lessons/collaborative-blog-with-jekyl...      5            1
2    _site/en/lessons/retired/intro-to-augmented-re...      4            2
3                       _site/en/contribute/index.html      4            3
4    _site/en/lessons/interactive-data-visualizatio...      4            4
..                                                 ...    ...          ...
118        _site/pt/licoes/instalacao-linux/index.html      1          118
119      _site/pt/licoes/instalacao-windows/index.html      1          119
120      _site/pt/licoes/introducao-mysql-r/index.html      1          120
121  _site/pt/licoes/sumarizacao-narrativas-web-pyt...      1          121
122                          _site/pt/sobre/index.html      1          122

[123 rows x 3 columns]

In [63]:
merged_df = df.merge(file_counts_df, on='file', how='outer').sort_values(by="count_index", ascending=True)

In [64]:
merged_df[merged_df.file.str.contains("_site/assets", na=False)]

Empty DataFrame
Columns: [file, line, message, count, count_index]
Index: []

In [30]:
import os
import re

EXTENSIONS = (".yml")

def replace_links_preserving_code_blocks(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Match code blocks (triple backticks) and inline code (`...`)
    code_blocks = list(re.finditer(r"(```.*?```|`[^`]*`)", content, re.DOTALL))
    modified = content
    offset = 0

    for match in code_blocks:
        start, end = match.span()
        segment = content[start:end]

        # Temporarily mark this section to skip
        placeholder = f"%%CODEBLOCK{start}%%"
        modified = modified[:start + offset] + placeholder + modified[end + offset:]
        offset += len(placeholder) - (end - start)

    # Replace all http:// with https://
    modified = re.sub(r"http://", "https://", modified)

    # Restore code blocks untouched
    for match in code_blocks:
        start = match.start()
        placeholder = f"%%CODEBLOCK{start}%%"
        modified = modified.replace(placeholder, match.group(0))

    if content != modified:
        print(f"✅ Updated: {file_path}")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(modified)

def process_all_files(root="."):
    for dirpath, _, filenames in os.walk(root):
        for fname in filenames:
            if fname.endswith(EXTENSIONS) and "ph_authors" in fname:
                replace_links_preserving_code_blocks(os.path.join(dirpath, fname))

process_all_files()

✅ Updated: ./_data/ph_authors.yml