# Fixing Links Notebook

Before running this notebook, make sure to run the following command in the terminal to install the required packages:

```bash
bundle install
make all
ruby parse_htmlproofer_log.rb 
```

Each command should be run separately and the final two commands create files for all the htmlproofer errors and warnings. This notebook loads the final csv file to help you see what links exists. You will also need to install the `pandas` library if you haven't already. You can do this by running:

```bash
pip install pandas
```

## Load Libraries and Data

In [46]:
import pandas as pd

In [47]:
df = pd.read_csv("htmlproofer-report.csv")
# Lower case the column names
df.columns = df.columns.str.lower()
print(f"Number of errors: {len(df)}")

Number of errors: 227

In [48]:
message_counts = df.message.value_counts().reset_index()
message_counts[(message_counts['count']>1) & (~message_counts.message.str.contains("HTTPS|https")) & (~message_counts.message.str.contains("does not have an alt attribute"))].to_dict(orient="records")

[{'message': "internally linking to /en/lessons/building-static-sites-with-jekyll-github-pages#writing-pages-and-posts; the file exists, but the hash 'writing-pages-and-posts' does not",
  'count': 3},
 {'message': "internally linking to /en/lessons/creating-network-diagrams-from-historical-sources#developing-a-coding-scheme; the file exists, but the hash 'developing-a-coding-scheme' does not",
  'count': 3},
 {'message': "internally linking to /es/guia-para-autores#paso-1-proponer-una-nueva-lección; the file exists, but the hash 'paso-1-proponer-una-nueva-lección' does not",
  'count': 2},
 {'message': "internally linking to /fr/consignes-auteurs#étape-1-proposer-une-nouvelle-leçon; the file exists, but the hash 'étape-1-proposer-une-nouvelle-leçon' does not",
  'count': 2},
 {'message': "internally linking to /pt/directrizes-autor#etapa-1-propor-uma-nova-lição; the file exists, but the hash 'etapa-1-propor-uma-nova-lição' does not",
  'count': 2},
 {'message': 'internally linking to ipp, which does not exist', 'count': 2},
 {'message': "internally linking to /en/lessons/clustering-with-scikit-learn-in-python#3-dimensionality-reduction-using-pca; the file exists, but the hash '3-dimensionality-reduction-using-pca' does not",
  'count': 2},
 {'message': "internally linking to /en/lessons/text-mining-with-extracted-features#start-a-notebook; the file exists, but the hash 'start-a-notebook' does not",
  'count': 2},
 {'message': "internally linking to /en/lessons/jupyter-notebooks#installing-jupyter-notebooks; the file exists, but the hash 'installing-jupyter-notebooks' does not",
  'count': 2},
 {'message': 'internally linking to /en/lessons/intro-to-powershell.html, which does not exist',
  'count': 2},
 {'message': "internally linking to /en/lessons/extracting-illustrated-pages#jupyter-notebooks; the file exists, but the hash 'jupyter-notebooks' does not",
  'count': 2},
 {'message': "internally linking to #google-vision-2; the file exists, but the hash 'google-vision-2' does not",
  'count': 2},
 {'message': 'internally linking to /en/lessons/intro-to-beautiful-soup.html, which does not exist',
  'count': 2},
 {'message': 'internally linking to /en/lessons/intro-to-bash.html, which does not exist',
  'count': 2},
 {'message': "internally linking to #Final-code; the file exists, but the hash 'Final-code' does not",
  'count': 2},
 {'message': 'internally linking to support-us#institutional-partner-programme, which does not exist',
  'count': 2},
 {'message': "internally linking to #paso-3-selecion-sistematica-y-reproducible-de-datos-individuales-para-la-lectura-atenta; the file exists, but the hash 'paso-3-selecion-sistematica-y-reproducible-de-datos-individuales-para-la-lectura-atenta' does not",
  'count': 2},
 {'message': 'internally linking to introduccion-a-bash, which does not exist',
  'count': 2},
 {'message': "internally linking to #Apêndice:AMatemáticaportrásdaAnálisedeCorrespondência; the file exists, but the hash 'Apêndice:AMatemáticaportrásdaAnálisedeCorrespondência' does not",
  'count': 2}]

In [52]:
print(f"Number of unique error messages: {len(message_counts)}")
message_counts[(message_counts['count']>1)]

Number of unique error messages: 145

                                              message  count
0   External link https://wiki.python.org/moin/Pyt...     13
1   External link https://komodoide.com/komodo-edi...      5
2   http://niche-canada.org/2018/03/23/a-decade-of...      4
3   http://clionauta.hypotheses.org/16979 is not a...      4
4   External link https://github.com/orgs/programm...      4
5   External link https://www.activestate.com/komo...      4
6   External link https://central.github.com/mac/l...      4
7   External link https://perso.ens-lyon.fr/matthi...      4
8   External link https://operas-eu.org/news-and-e...      4
9   image /images/website/index/woman-using-tabula...      3
10  http://www.loc.gov/maps/collections is not an ...      3
11  http://programminghistorian.org/ is not an HTT...      3
12  External link https://internetarchive.readthed...      3
13  External link https://www.activestate.com/prod...      3
14  External link https://www.mappingthegayguides....      3
15  internally linking to /en/lessons/building-sta...      3
16  internally linking to /en/lessons/creating-net...      3
17  image /images/website/individual/red-bird-on-b...      2
18  image /images/website/ipp/bird-with-eggs-nest....      2
19  http://dx.doi.org/10.1145/2682571.2797068 is n...      2
20  http://www.gazetteer.org.uk/index.php is not a...      2
21  http://www.gov.pe.ca/gis/download.php3?name=fo...      2
22              http://tropy.org is not an HTTPS link      2
23  External link https://internetarchive.readthed...      2
24  External link https://textcreationpartnership....      2
25  External link https://www.hastac.org/blogs/har...      2
26  External link https://devchat.cachefly.net/rub...      2
27  External link https://notepad-plus-plus.org/do...      2
28  External link https://www.activestate.com/prod...      2
29  internally linking to /es/guia-para-autores#pa...      2
30  internally linking to /fr/consignes-auteurs#ét...      2
31  internally linking to /pt/directrizes-autor#et...      2
32    internally linking to ipp, which does not exist      2
33  internally linking to /en/lessons/clustering-w...      2
34  internally linking to /en/lessons/text-mining-...      2
35  internally linking to /en/lessons/jupyter-note...      2
36  internally linking to /en/lessons/intro-to-pow...      2
37  internally linking to /en/lessons/extracting-i...      2
38  internally linking to #google-vision-2; the fi...      2
39  internally linking to /en/lessons/intro-to-bea...      2
40  internally linking to /en/lessons/intro-to-bas...      2
41  internally linking to #Final-code; the file ex...      2
42  internally linking to support-us#institutional...      2
43  internally linking to #paso-3-selecion-sistema...      2
44  internally linking to introduccion-a-bash, whi...      2
45  internally linking to #Apêndice:AMatemáticapor...      2

In [50]:
df

,file,line,message
0,_site/en/lessons/retired/OCR-with-Tesseract-an...,276,internal image /gallery/OCR-with-Tesseract-and...
1,_site/es/donaciones/index.html,250,image /images/website/individual/red-bird-on-b...
2,_site/es/index.html,252,image /images/website/index/woman-using-tabula...
3,_site/es/pia/index.html,250,image /images/website/ipp/bird-with-eggs-nest....
4,_site/fr/consignes-auteurs/index.html,250,image /images/website/woman-at-writing-desk.pn...
...,...,...,...
222,_site/pt/licoes/introducao-jupyter-notebooks/i...,559,internally linking to /pt/licoes/extrair-pagin...
223,_site/pt/licoes/introducao-jupyter-notebooks/i...,628,internally linking to #Usando-Jupyter-Notebook...
224,_site/pt/licoes/introducao-mysql-r/index.html,1721,internally linking to #Conectando-a-um-banco-d...
225,_site/pt/licoes/sumarizacao-narrativas-web-pyt...,537,internally linking to /en/lessons/jupyter-note...
226,_site/pt/sobre/index.html,276,"internally linking to /pt/apoie-nos, which doe..."

In [51]:
file_counts = df.file.value_counts().reset_index()
print(f"Number of unique files with errors: {len(file_counts)}")
file_counts[file_counts['count']>1]

Number of unique files with errors: 139

                                                 file  count
0   _site/en/lessons/collaborative-blog-with-jekyl...      5
1   _site/en/lessons/retired/intro-to-augmented-re...      4
2                      _site/en/contribute/index.html      4
3   _site/en/lessons/interactive-data-visualizatio...      4
4   _site/en/lessons/retired/graph-databases-and-S...      4
5                                 _site/pt/index.html      3
6   _site/en/lessons/detecting-text-reuse-with-pas...      3
7   _site/en/lessons/exploring-and-analyzing-netwo...      3
8                        _site/en/research/index.html      3
9                   _site/es/investigacion/index.html      3
10                      _site/fr/recherche/index.html      3
11             _site/pt/directrizes-editor/index.html      3
12                       _site/pt/pesquisa/index.html      3
13  _site/en/lessons/retired/getting-started-with-...      3
14  _site/en/lessons/shiny-leaflet-newspaper-map-t...      3
15  _site/es/lecciones/mineria-de-datos-en-interne...      3
16  _site/es/lecciones/retirada/introduccion-contr...      3
17              _site/en/author-guidelines/index.html      3
18       _site/en/lesson-retirement-policy/index.html      3
19  _site/en/lessons/clustering-visualizing-word-e...      3
20            _site/en/lessons/json-and-jq/index.html      3
21  _site/en/lessons/ocr-with-google-vision-and-te...      3
22                     _site/en/supporters/index.html      3
23          _site/en/translator-guidelines/index.html      3
24  _site/es/lecciones/construir-repositorio-de-fu...      3
25  _site/es/lecciones/retirada/sparql-datos-abier...      3
26    _site/es/politica-retirada-lecciones/index.html      3
27        _site/pt/licoes-politica-remocao/index.html      3
28                             _site/fr/pi/index.html      2
29              _site/en/editor-guidelines/index.html      2
30                    _site/es/guia-editor/index.html      2
31  _site/es/lecciones/gestionar-fuentes-primarias...      2
32  _site/fr/lecons/detecter-la-reutilisation-de-t...      2
33  _site/en/lessons/beginners-guide-to-twitter-da...      2
34  _site/en/lessons/crowdsourced-data-normalizati...      2
35  _site/en/lessons/data-mining-the-internet-arch...      2
36  _site/en/lessons/introduction-and-installation...      2
37     _site/en/lessons/linux-installation/index.html      2
38    _site/es/lecciones/instalacion-linux/index.html      2
39  _site/es/lecciones/introduccion-e-instalacion/...      2
40  _site/fr/lecons/installer-ide-python-linux/ind...      2
41  _site/fr/lecons/introduction-et-installation/i...      2
42        _site/pt/licoes/instalacao-linux/index.html      2
43          _site/pt/licoes/instalacao-mac/index.html      2
44  _site/pt/licoes/introducao-instalacao-python/i...      2
45  _site/en/lessons/corpus-analysis-with-spacy/in...      2
46  _site/es/lecciones/introduccion-a-powershell/i...      2
47  _site/es/lecciones/lectura-escalable-de-datos-...      2
48  _site/es/lecciones/topic-modeling-y-mallet/ind...      2
49  _site/fr/lecons/concevoir-base-donnees-nodegoa...      2
50  _site/fr/lecons/enrichir-donnees-reconciliatio...      2
51  _site/fr/lecons/generer-jeu-donnees-texte-ocr/...      2
52  _site/pt/licoes/analise-correspondencia-pesqui...      2
53  _site/pt/licoes/introducao-jupyter-notebooks/i...      2

In [34]:
df[df.file == "_site/en/about/index.html"].to_dict(orient="records")

[]

In [35]:
file_counts

                                                  file  count
0    _site/en/lessons/collaborative-blog-with-jekyl...      5
1    _site/en/lessons/retired/intro-to-augmented-re...      4
2    _site/en/lessons/interactive-data-visualizatio...      4
3    _site/en/lessons/retired/graph-databases-and-S...      4
4                                  _site/pt/index.html      3
..                                                 ...    ...
134  _site/pt/licoes/git-ferramenta-metodologica-pr...      1
135      _site/pt/licoes/introducao-mysql-r/index.html      1
136  _site/pt/licoes/sumarizacao-narrativas-web-pyt...      1
137  _site/pt/licoes/transcricao-automatica-grafias...      1
138                          _site/pt/sobre/index.html      1

[139 rows x 2 columns]

In [36]:
file_counts_df = df.file.value_counts().reset_index()
file_counts_df['count_index'] = file_counts_df.index

file_counts_df

                                                  file  count  count_index
0    _site/en/lessons/collaborative-blog-with-jekyl...      5            0
1    _site/en/lessons/retired/intro-to-augmented-re...      4            1
2    _site/en/lessons/interactive-data-visualizatio...      4            2
3    _site/en/lessons/retired/graph-databases-and-S...      4            3
4                                  _site/pt/index.html      3            4
..                                                 ...    ...          ...
134  _site/pt/licoes/git-ferramenta-metodologica-pr...      1          134
135      _site/pt/licoes/introducao-mysql-r/index.html      1          135
136  _site/pt/licoes/sumarizacao-narrativas-web-pyt...      1          136
137  _site/pt/licoes/transcricao-automatica-grafias...      1          137
138                          _site/pt/sobre/index.html      1          138

[139 rows x 3 columns]

In [37]:
merged_df = df.merge(file_counts_df, on='file', how='outer').sort_values(by="count_index", ascending=True)

In [38]:
merged_df

,file,line,message,count,count_index
20,_site/en/lessons/collaborative-blog-with-jekyl...,1507,internally linking to /en/lessons/building-sta...,5,0
19,_site/en/lessons/collaborative-blog-with-jekyl...,1147,internally linking to /en/lessons/building-sta...,5,0
18,_site/en/lessons/collaborative-blog-with-jekyl...,1114,internally linking to /en/lessons/building-sta...,5,0
17,_site/en/lessons/collaborative-blog-with-jekyl...,1017,internally linking to /en/lessons/building-sta...,5,0
16,_site/en/lessons/collaborative-blog-with-jekyl...,950,internally linking to /en/lessons/building-sta...,5,0
...,...,...,...,...,...
198,_site/pt/licoes/git-ferramenta-metodologica-pr...,1002,internally linking to #comandos-basicos; the f...,1,134
208,_site/pt/licoes/introducao-mysql-r/index.html,1721,internally linking to #Conectando-a-um-banco-d...,1,135
212,_site/pt/licoes/sumarizacao-narrativas-web-pyt...,537,internally linking to /en/lessons/jupyter-note...,1,136
213,_site/pt/licoes/transcricao-automatica-grafias...,708,internally linking to #definicao-de-necessidad...,1,137
218,_site/pt/sobre/index.html,276,"internally linking to /pt/apoie-nos, which doe...",1,138

In [39]:
merged_df[merged_df.file.str.contains("_site/en/lessons/collaborative-blog-with-jekyl")].to_clipboard()

In [6]:
merged_df[merged_df.file.str.contains("_site/assets/from-html-to-list-of-words-1/", na=False)].message.value_counts()

message
'a' tag is missing a reference                                                                                              12
internal image i/genericThumb.jpg does not exist                                                                             5
internally linking to static/Contact.jsp, which does not exist                                                               2
internally linking to images.jsp?doc=178006280090, which does not exist                                                      2
internally linking to images.jsp?doc=178006280088, which does not exist                                                      2
internally linking to images.jsp?doc=178006280087, which does not exist                                                      2
internally linking to images.jsp?doc=178006280089, which does not exist                                                      2
internally linking to images.jsp?doc=178006280084, which does not exist                                                      2
internally linking to forms/formMain.jsp, which does not exist                                                               2
internally linking to browse.jsp?dir=ordinarysAccounts, which does not exist                                                 1
internally linking to css/print.css, which does not exist                                                                    1
internal script reference a.js does not exist                                                                                1
internally linking to static/Crimes.jsp#riot, which does not exist                                                           1
External link https://www.sheffield.ac.uk/hri/ failed (status code 403)                                                      1
internally linking to index.jsp, which does not exist                                                                        1
External link https://markhadley.com failed with something very wrong.                                                       1
internally linking to static/Site-map.jsp, which does not exist                                                              1
internally linking to css/screen.css, which does not exist                                                                   1
internally linking to static/Legal-info.jsp, which does not exist                                                            1
internally linking to browse.jsp?foo=bar&path=sessionsPapers/17800628.xml&div=t17800628-33&xml=yes, which does not exist     1
internally linking to static/Guides.jsp, which does not exist                                                                1
internally linking to browse.jsp?dir=sessionsPapers, which does not exist                                                    1
internally linking to static/History.jsp, which does not exist                                                               1
internally linking to browse.jsp?div=t17800628-34, which does not exist                                                      1
internally linking to browse.jsp?div=t17800628-32, which does not exist                                                      1
internally linking to static/Punishment.jsp#death, which does not exist                                                      1
internally linking to static/Verdicts.jsp#guilty, which does not exist                                                       1
internally linking to static/Crimes.jsp#breakingpeace, which does not exist                                                  1
internally linking to static/Proceedings.jsp, which does not exist                                                           1
internally linking to static/Project.jsp, which does not exist                                                               1
internally linking to a.css, which does not exist                                                                            1
Name: count, dtype: int64

In [7]:
merged_df[merged_df.message == "internal image i/genericThumb.jpg does not exist"].file.value_counts()

file
_site/assets/from-html-to-list-of-words-1/obo-t17800628-33.html            5
_site/assets/normaliser-donnees-textuelles-python/obo-t17800628-33.html    5
Name: count, dtype: int64

In [8]:
merged_df[merged_df.file.str.contains("_site/en/lessons/building-static-sites-with-jekyll-github-pages", na=False)]

,file,line,message,count,count_index
412,_site/en/lessons/building-static-sites-with-je...,1334,External link https://support.native-instrumen...,10,88
411,_site/en/lessons/building-static-sites-with-je...,66,External link https://maxcdn.bootstrapcdn.com/...,10,88
410,_site/en/lessons/building-static-sites-with-je...,57,External link https://maxcdn.bootstrapcdn.com/...,10,88
406,_site/en/lessons/building-static-sites-with-je...,117,'a' tag is missing a reference,10,88
413,_site/en/lessons/building-static-sites-with-je...,1474,External link https://jekyllthemes.org/ failed...,10,88
414,_site/en/lessons/building-static-sites-with-je...,1545,External link https://jekyll-windows.juthilo.c...,10,88
415,_site/en/lessons/building-static-sites-with-je...,1548,External link https://chronicle.com/blogs/prof...,10,88
407,_site/en/lessons/building-static-sites-with-je...,136,'a' tag is missing a reference,10,88
408,_site/en/lessons/building-static-sites-with-je...,173,'a' tag is missing a reference,10,88
409,_site/en/lessons/building-static-sites-with-je...,199,'a' tag is missing a reference,10,88

In [30]:
import os
import re

EXTENSIONS = (".yml")

def replace_links_preserving_code_blocks(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Match code blocks (triple backticks) and inline code (`...`)
    code_blocks = list(re.finditer(r"(```.*?```|`[^`]*`)", content, re.DOTALL))
    modified = content
    offset = 0

    for match in code_blocks:
        start, end = match.span()
        segment = content[start:end]

        # Temporarily mark this section to skip
        placeholder = f"%%CODEBLOCK{start}%%"
        modified = modified[:start + offset] + placeholder + modified[end + offset:]
        offset += len(placeholder) - (end - start)

    # Replace all http:// with https://
    modified = re.sub(r"http://", "https://", modified)

    # Restore code blocks untouched
    for match in code_blocks:
        start = match.start()
        placeholder = f"%%CODEBLOCK{start}%%"
        modified = modified.replace(placeholder, match.group(0))

    if content != modified:
        print(f"✅ Updated: {file_path}")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(modified)

def process_all_files(root="."):
    for dirpath, _, filenames in os.walk(root):
        for fname in filenames:
            if fname.endswith(EXTENSIONS) and "ph_authors" in fname:
                replace_links_preserving_code_blocks(os.path.join(dirpath, fname))

process_all_files()

✅ Updated: ./_data/ph_authors.yml